# Generated by Django 2.2.5 on 2020-05-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddredd',
            new_name='ShippingAddress',
        ),
    ]
